### ISSUE TITLE
what's the difference between classeur and stackedit?

### ISSUE THREAD

**Issue by colcord** [classeur/classeur.github.io#1]
Stackedit lets me work with dropbox. Classeur doesn't.
I'm looking for a workflow that lets me keep my own .txt markdown documents.
I want to be able to edit them on my android devices, my linux laptops, my work browser.
And then process them with pandoc.
Can I do those things with Classeur?
I had some issues with Stackedit.
thanks.

**Comment by benweet** [comment]
Classeur has it's own file storage/synchronizaion mechanism (no auto-sync with Google Drive or Dropbox). Working with your own files will only be possible with the Classeur desktop application. Then you will be able to use Google Drive/Dropbox official apps to sync your files.
